.DEFAULT_GOAL := help

BUILD_DIR   ?= $(CURDIR)/build
CONFIG      ?= Debug
PREFIX      ?= $(HOME)/.local
APP_DEST    ?= /Applications
XCODEBUILD  := xcodebuild -project App/ScreenGrab.xcodeproj -scheme ScreenGrab -configuration $(CONFIG) -derivedDataPath $(BUILD_DIR)
APP         := $(BUILD_DIR)/Build/Products/$(CONFIG)/ScreenGrab.app

.PHONY: help generate build cli test run install install-cli list-devices clean

help: ## Show this help.
	@awk 'BEGIN { printf "ScreenGrab developer targets\n\nUsage:\n  make <target> [CONFIG=Release] [PREFIX=~/.local] [APP_DEST=/Applications]\n\nTargets:\n" } /^[a-zA-Z0-9_.-]+:.*##/ { split($$0, a, ":.*## "); printf "  %-14s %s\n", a[1], a[2] }' $(MAKEFILE_LIST)
	@printf "\nPrerequisites: Xcode 27+, xcodegen, shark (brew). Signing team goes into App/Config/Local.xcconfig.\n"

generate: ## Generate the Xcode project (XcodeGen).
	@test -f App/ScreenGrab/Resources/Shark.swift || echo '// regenerated by the Shark build phase' > App/ScreenGrab/Resources/Shark.swift
	cd App && xcodegen generate

build: generate ## Build the menu-bar app.
	$(XCODEBUILD) build | xcbeautify -qq

cli: ## Build the iphone-screenshot CLI (release).
	swift build -c release --product iphone-screenshot

test: ## Run the ScreenGrabKit unit tests.
	swift test

run: build ## Build and launch the app (logs to the terminal).
	LOGLEVEL=TRACE OS_ACTIVITY_MODE=disabled $(APP)/Contents/MacOS/ScreenGrab

install: CONFIG := Release
install: build ## Install the app to APP_DEST (default /Applications).
	rm -rf "$(APP_DEST)/ScreenGrab.app"
	cp -R "$(APP)" "$(APP_DEST)/"

install-cli: cli ## Install iphone-screenshot to PREFIX/bin.
	mkdir -p "$(PREFIX)/bin"
	install -m 755 .build/release/iphone-screenshot "$(PREFIX)/bin/iphone-screenshot"

list-devices: ## List paired iPhones/iPads with their availability.
	swift run -q iphone-screenshot list

clean: ## Remove build artifacts.
	rm -rf .build build App/ScreenGrab.xcodeproj
